[package]
name = "UTMMBackend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
tokio = { version = "1.44.1", features = ["full"] }
tower-http = { version = "0.6.2", features = ["full"] }
log = "0.4"
env_logger = "0.10"
once_cell = "1.21.3"
